import bioCommons, primer3
'''
Prepare all the templates and design PCR primers
Mutation allele is generated here
But the extra mutation of ARMS is generated by the function of bioCommons.armsPcrTemplate

Output files:
	masked.template.wild.txt
	masked.template.mutation.txt
	masked.template.mutationTemplate.minus2.txt
	masked.template.wtTemplate.minus2.txt
	masked.template.mutationTemplate.minus3.txt
	masked.template.wtTemplate.minus3.txt
'''

def getAllArmsTemplates(snpID, wtAllele, mutAllele, pcrMaskedTemplate):

	position = int(len(pcrMaskedTemplate.template)/2)
	filename = f"{snpID}/masked.template"

	bioCommons.ScreenOutput.add(f"WildTemplate = {pcrMaskedTemplate.center5}")
	bioCommons.writeFile(pcrMaskedTemplate.template, filename + '.wild.txt')

	# Based on the masked wild type template, generate the masked mutation type template
	pcrMaskedMutTemplate = pcrMaskedTemplate.mute(position, mutAllele)
	bioCommons.ScreenOutput.add(f"MutationTemplate = {pcrMaskedMutTemplate.center5}")
	bioCommons.writeFile(pcrMaskedMutTemplate.template, filename + '.mutation.txt')

	# create and return mutation template with both -2 changes
	bioCommons.ScreenOutput.add("\nAdditional mutation at -2 position")
	wt1, mut1 = bioCommons.armsPcrTemplate(pcrMaskedTemplate, pcrMaskedMutTemplate, 1)

	bioCommons.ScreenOutput.add("\nMutation template")
	bioCommons.writeFile(mut1.template, filename + '.mutationTemplate.minus2.txt')
	primer3.designPrimers(filename + '.mutationTemplate.minus2.txt')

	bioCommons.ScreenOutput.add("\nWild template")
	bioCommons.writeFile(wt1.template, filename + ".wtTemplate.minus2.txt")
	primer3.designPrimers(filename + '.wtTemplate.minus2.txt')

	# create and return mutation template with both -3 changes
	bioCommons.ScreenOutput.add("\nAdditional mutation at -3 position")
	wt2, mut2 = bioCommons.armsPcrTemplate(pcrMaskedTemplate, pcrMaskedMutTemplate, 2)

	bioCommons.ScreenOutput.add("\nMutation template")
	bioCommons.writeFile(mut2.template, filename + '.mutationTemplate.minus3.txt')
	primer3.designPrimers(filename + '.mutationTemplate.minus3.txt')

	bioCommons.ScreenOutput.add("\nWild template")
	bioCommons.writeFile(wt2.template, filename + '.wtTemplate.minus3.txt')
	primer3.designPrimers(filename + '.wtTemplate.minus3.txt')
